flowchart TB
    DD[Dewan Direksi<br/>3-5 orang]
    DU[Direktur Utama]
    
    DD --> DU
    
    DU --> DT[Direktur Teknologi]
    DU --> DO[Direktur Operasional]
    DU --> DM[Direktur Marketing]
    DU --> DF[Direktur Keuangan]
    
    DT --> Dev[Development Team<br/>10-15 orang]
    DT --> IT[IT Operations<br/>3-5 orang]
    DT --> Data[Data Team<br/>3-5 orang]
    
    DO --> Part[Partnership Team<br/>5-10 orang]
    DO --> CS[Customer Service<br/>10-15 orang]
    DO --> Field[Field Team<br/>20-30 orang]
    DO --> QA[Quality Assurance<br/>3-5 orang]
    
    DM --> Digital[Digital Marketing<br/>5-8 orang]
    DM --> Content[Content Team<br/>5-8 orang]
    DM --> Comm[Community Manager<br/>3-5 orang]
    
    DF --> Acc[Accounting<br/>3-5 orang]
    DF --> HR[HR & Admin<br/>3-5 orang]