sequenceDiagram
    participant W as Wisatawan
    participant P as Visit Sulsel
    participant M as Mitra Guide

    W->>P: 1. Pilih Area
    W->>P: 2. Pilih Tanggal
    W->>P: 3. Bayar
    P->>M: 4. Assign Guide
    P->>W: 5. Info Guide
    M->>W: 6. Layani
